# numpy
* Nemerical Python 과학적, 산업적 연산을 위한 패키지
* 다차원 배열, 행렬 연산에 주로 사용
* numpy는 python의 list와 비슷한 자료형
* 순서가 있는 자료형
* 인덱싱, 슬라이싱 가능
* 반복문에 넣어서 한개씩 꺼내는 것도 가능 
* 파이썬 list와의 차이점은 자료형이 1개만 들어간다는 점이 다르다. 

# 차원
* 0차원 = 점 . 스칼라 a = 10
* 1차원 = 선 ------- 방향이 없는 벡터, 배열, list, tuple
  * 벡터(vector): 방향을 가진 데이터 

* 2차원 = 면, 가로, 세로, DB테이블, excel의 sheet, 행렬, DataFrame, matrix
  * 행벡터: 행이 1개인 벡터 [[1,2,3,4]]
  * 열벡터: 열이 1개인 벡터<br> 
            [[1],<br>
             [2],<br>
             [3],<br>
             [4]]
* 3차원 = 입체, 가로, 세로, 깊이, 정육면체, 주사위
* 4차원 = 3차원 요소가 2개 이상 묶여 있는 상태
* 5차원 = 4차원 요소가 2개 이상 묶여 있는 상태 

* 2차원 데이터가 여러개 묶여있는 게 3차원 
* 3차원 // 4차원 

In [61]:
import pandas as pd
import numpy as np

In [62]:
#numpy의 기본 자료형 nd.array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [19]:
a[0]

np.int64(1)

In [20]:
print(a[-1])

5


In [21]:
print(a[:3])

[1 2 3]


* 차원을 출력하는 메서드 .ndim
* 차원의 형태를 출력하는 메서드 .shape

In [22]:
# 스칼라, 0차원,
s = 10

In [23]:
s.ndim

AttributeError: 'int' object has no attribute 'ndim'

In [24]:
# a는 방향이 없는 벡터이므로 1차원
a.ndim

1

In [25]:
# 데이터가 5개 있는 방향 없는 벡터
a.shape

(5,)

In [63]:
# 세로로 방향을 가진 열벡터
a2 = np.array([[1],[2],[3],[4],[5]])
a2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [27]:
print(a2.ndim)
print(a2.shape)

2
(5, 1)


In [64]:
# 행벡터 2차원 행이 1개인 벡터 
a3 = np.array([[1,2,3,4,5]])
print(a3.ndim)
print(a3.shape)

2
(1, 5)


In [65]:
# 2차원 데이터 matrix, dataframe
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
print(c.ndim)
print(c.shape)

2
(2, 5)


In [66]:
# 3차원 데이터
d = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])
d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [32]:
print(d.ndim)
print(d.shape)
# 뒤에 있는 게 무조건 행과 열! (2행 5열짜리 2개 있다는 의미)

3
(2, 2, 5)


In [67]:
# 4차원 데이터
e = np.array([[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]],[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]]])
e

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]],


       [[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]])

In [34]:
print(e.ndim)
print(e.shape)

4
(2, 3, 2, 5)


In [35]:
# 5차원 데이터
f = np.array([[[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]],[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]]],[[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]],[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]]]])
f

array([[[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]],



       [[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]]])

In [36]:
print(f.ndim)
print(f.shape)

5
(2, 2, 3, 2, 5)


# numpy를 사용하는 이유
* 행렬 연산이 쉽고 빠르기 때문

In [37]:
# 스칼라 연산
a = 10
b = 5
scalar = a + b
print(scalar)

15


In [40]:
# 1차원 벡터 데이터의 연산 
b1 = [1,2,3,4,5]

In [39]:
# b1의 모든 요소에 10을 곱한 후 다시 리스트로 만드세요
result = []
for num in b1:
    result.append(num*10)
result

[10, 20, 30, 40, 50]

In [41]:
result2 = [num*10 for num in b1]
result2

[10, 20, 30, 40, 50]

In [42]:
a2 * 10

array([[10],
       [20],
       [30],
       [40],
       [50]])

In [43]:
a3 * 10

array([[10, 20, 30, 40, 50]])

# 2차원 데이터에 10을 곱하는 경우

In [44]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [45]:
c.shape

(2, 5)

* 파이썬 기본 문법으로 했을 때

In [46]:
result = []
for num1 in c:
    temp1 = []
    for num2 in num1:
        temp1.append(num2)
    result.append(temp1)
result

[[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)],
 [np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10)]]

In [47]:
result = []
for num1 in c:
    temp = []
    for num2 in num1:
        temp.append(num2*10)
    result.append(temp)
result

[[np.int64(10), np.int64(20), np.int64(30), np.int64(40), np.int64(50)],
 [np.int64(60), np.int64(70), np.int64(80), np.int64(90), np.int64(100)]]

In [48]:
np.array(result).shape

(2, 5)

In [49]:
c * 10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [50]:
d * 10

array([[[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100]],

       [[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100]]])

In [51]:
d.shape

(2, 2, 5)

# .size
* 배열 안에 있는 요소의 총 개수가 몇 개인지 

In [55]:
a3

array([[1, 2, 3, 4, 5]])

In [52]:
len(a3)

1

In [53]:
a3.shape

(1, 5)

In [54]:
len(a3[0])

5

In [56]:
hap = 0
for i in c:
    hap += len(i)
hap

10

In [57]:
a3.size

5

In [58]:
c.size

10

In [59]:
d.size

20

# .dtype
* 데이터 타입이 무엇인지 출력

In [68]:
d.dtype

dtype('int64')

In [69]:
d2 = d/2
d2

array([[[0.5, 1. , 1.5, 2. , 2.5],
        [3. , 3.5, 4. , 4.5, 5. ]],

       [[0.5, 1. , 1.5, 2. , 2.5],
        [3. , 3.5, 4. , 4.5, 5. ]]])

In [70]:
d2.dtype

dtype('float64')

# .astype(데이터타입명)
* 데이터 타입을 바꾸고 싶을 때

In [72]:
d2.astype(int)

array([[[0, 1, 1, 2, 2],
        [3, 3, 4, 4, 5]],

       [[0, 1, 1, 2, 2],
        [3, 3, 4, 4, 5]]])

In [73]:
d2

array([[[0.5, 1. , 1.5, 2. , 2.5],
        [3. , 3.5, 4. , 4.5, 5. ]],

       [[0.5, 1. , 1.5, 2. , 2.5],
        [3. , 3.5, 4. , 4.5, 5. ]]])

In [74]:
d2.astype(str)

array([[['0.5', '1.0', '1.5', '2.0', '2.5'],
        ['3.0', '3.5', '4.0', '4.5', '5.0']],

       [['0.5', '1.0', '1.5', '2.0', '2.5'],
        ['3.0', '3.5', '4.0', '4.5', '5.0']]], dtype='<U32')

In [75]:
d2.dtype #표현할 수 있는 범위를 뜻함(64)

dtype('float64')

In [76]:
d2.astype('float32')

array([[[0.5, 1. , 1.5, 2. , 2.5],
        [3. , 3.5, 4. , 4.5, 5. ]],

       [[0.5, 1. , 1.5, 2. , 2.5],
        [3. , 3.5, 4. , 4.5, 5. ]]], dtype=float32)

In [77]:
d2.astype('float16')

array([[[0.5, 1. , 1.5, 2. , 2.5],
        [3. , 3.5, 4. , 4.5, 5. ]],

       [[0.5, 1. , 1.5, 2. , 2.5],
        [3. , 3.5, 4. , 4.5, 5. ]]], dtype=float16)

# ndarray 만들기
* ndarray는 numpy의 기본 자료형
* 자료형은 반드시 1가지만 넣을 수 있다.
* 2개 이상의 자료형이 있는 경우 문자 -> 실수 - 정수 순으로 우선 순위가 매겨진다.

In [78]:
e = np.array([1,2,3,4,5])
e

array([1, 2, 3, 4, 5])

In [82]:
e2 = np.array([1,2,3.14,4,5])
print(e2.dtype)
e2

float64


array([1.  , 2.  , 3.14, 4.  , 5.  ])

In [81]:
e3 = np.array([1,2,3.14,"4",5])
print(e2.dtype)
e3

<U32


array(['1', '2', '3.14', '4', '5'], dtype='<U32')

# np.arange(시작, 끝, step)

In [83]:
a = np.arange(1, 11, 2)
a

array([1, 3, 5, 7, 9])

In [84]:
a2 = np.arange(11, 1, -3)
a2

array([11,  8,  5,  2])

In [85]:
# 1-100까지 있는 array
a3 = np.arange(1, 101)
a3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [86]:
print(a3.ndim, a3.shape)

1 (100,)


# .reshape(행, 열)
* ndarray의 모양을 자유롭게 변형시켜주는 메서드 

In [88]:
a4 = a3.reshape(20, 5)
print(a4.ndim, a4.shape)
a4

2 (20, 5)


array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [89]:
a4 = a4.reshape(5,2,2,5)
print(a4.ndim, a4.shape)
a4

4 (5, 2, 2, 5)


array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10]],

        [[ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]]],


       [[[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30]],

        [[ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]]],


       [[[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50]],

        [[ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70]],

        [[ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]]],


       [[[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90]],

        [[ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]]]])

In [93]:
a5 = a3.reshape(2,-1,2)
print(a5.ndim, a5.shape)
a5

3 (2, 25, 2)


array([[[  1,   2],
        [  3,   4],
        [  5,   6],
        [  7,   8],
        [  9,  10],
        [ 11,  12],
        [ 13,  14],
        [ 15,  16],
        [ 17,  18],
        [ 19,  20],
        [ 21,  22],
        [ 23,  24],
        [ 25,  26],
        [ 27,  28],
        [ 29,  30],
        [ 31,  32],
        [ 33,  34],
        [ 35,  36],
        [ 37,  38],
        [ 39,  40],
        [ 41,  42],
        [ 43,  44],
        [ 45,  46],
        [ 47,  48],
        [ 49,  50]],

       [[ 51,  52],
        [ 53,  54],
        [ 55,  56],
        [ 57,  58],
        [ 59,  60],
        [ 61,  62],
        [ 63,  64],
        [ 65,  66],
        [ 67,  68],
        [ 69,  70],
        [ 71,  72],
        [ 73,  74],
        [ 75,  76],
        [ 77,  78],
        [ 79,  80],
        [ 81,  82],
        [ 83,  84],
        [ 85,  86],
        [ 87,  88],
        [ 89,  90],
        [ 91,  92],
        [ 93,  94],
        [ 95,  96],
        [ 97,  98],
        [ 99, 100]

# flatten()
* 다차원 배열을 1차원으로 모아서 펼쳐줌

In [95]:
a5.shape

(2, 25, 2)

In [96]:
a6 = a5.flatten()
print(a6.shape)
a6

(100,)


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

# np.flip()
* 행열의 순서를 뒤집을 때 

In [99]:
a5 = np.arange(1, 21)
a5 = a5.reshape(-1, 2,2)
print(a5.ndim, a5.shape)
a5

3 (5, 2, 2)


array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])

In [100]:
a2[::-1]

array([ 2,  5,  8, 11])

In [101]:
a5[::-1]

array([[[17, 18],
        [19, 20]],

       [[13, 14],
        [15, 16]],

       [[ 9, 10],
        [11, 12]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 1,  2],
        [ 3,  4]]])

In [103]:
np.flip(a5)

array([[[20, 19],
        [18, 17]],

       [[16, 15],
        [14, 13]],

       [[12, 11],
        [10,  9]],

       [[ 8,  7],
        [ 6,  5]],

       [[ 4,  3],
        [ 2,  1]]])

# np.linstace(시작, 끝, 구간 수)
* 정해진 숫자 범위 안에서 균등하게 구간을 나눌 때

In [105]:
# 1에서 10까지 10개로 균등하게 나누기
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [106]:
# 1에서 10까지 33개로 균등하게 나누기
np.linspace(1, 10, 33)

array([ 1.     ,  1.28125,  1.5625 ,  1.84375,  2.125  ,  2.40625,
        2.6875 ,  2.96875,  3.25   ,  3.53125,  3.8125 ,  4.09375,
        4.375  ,  4.65625,  4.9375 ,  5.21875,  5.5    ,  5.78125,
        6.0625 ,  6.34375,  6.625  ,  6.90625,  7.1875 ,  7.46875,
        7.75   ,  8.03125,  8.3125 ,  8.59375,  8.875  ,  9.15625,
        9.4375 ,  9.71875, 10.     ])

In [107]:
# 1에서 10까지 539개로 균등하게 나누기
np.linspace(1, 10, 539)

array([ 1.        ,  1.01672862,  1.03345725,  1.05018587,  1.0669145 ,
        1.08364312,  1.10037175,  1.11710037,  1.133829  ,  1.15055762,
        1.16728625,  1.18401487,  1.20074349,  1.21747212,  1.23420074,
        1.25092937,  1.26765799,  1.28438662,  1.30111524,  1.31784387,
        1.33457249,  1.35130112,  1.36802974,  1.38475836,  1.40148699,
        1.41821561,  1.43494424,  1.45167286,  1.46840149,  1.48513011,
        1.50185874,  1.51858736,  1.53531599,  1.55204461,  1.56877323,
        1.58550186,  1.60223048,  1.61895911,  1.63568773,  1.65241636,
        1.66914498,  1.68587361,  1.70260223,  1.71933086,  1.73605948,
        1.7527881 ,  1.76951673,  1.78624535,  1.80297398,  1.8197026 ,
        1.83643123,  1.85315985,  1.86988848,  1.8866171 ,  1.90334572,
        1.92007435,  1.93680297,  1.9535316 ,  1.97026022,  1.98698885,
        2.00371747,  2.0204461 ,  2.03717472,  2.05390335,  2.07063197,
        2.08736059,  2.10408922,  2.12081784,  2.13754647,  2.15

# 정렬과 순위(sort, argsort)
* np.sort() 실제로 정렬된 값을 리턴
* np.arrgsort() 정렬 했을 때의 인덱스 순서를 리턴(원자료의 변형없이 작업하고 싶을 때)
  * 누가 1위인지 1위의 위치를 알려준다.

In [108]:
f = np.array([5,7,11,1,3,54,0,0.5,68])
f

array([ 5. ,  7. , 11. ,  1. ,  3. , 54. ,  0. ,  0.5, 68. ])

In [111]:
#f.sort()
print(sorted(f))

[np.float64(0.0), np.float64(0.5), np.float64(1.0), np.float64(3.0), np.float64(5.0), np.float64(7.0), np.float64(11.0), np.float64(54.0), np.float64(68.0)]


In [112]:
np.sort(f)

array([ 0. ,  0.5,  1. ,  3. ,  5. ,  7. , 11. , 54. , 68. ])

In [113]:
f

array([ 0. ,  0.5,  1. ,  3. ,  5. ,  7. , 11. , 54. , 68. ])

In [ ]:
np.sorrt(f)

In [114]:
f

array([ 0. ,  0.5,  1. ,  3. ,  5. ,  7. , 11. , 54. , 68. ])

In [115]:
arr = np.array([
    [[5,2,8],
    [1,6,7]],
    
    [[4,9,3],
    [0,2,1]]
])

In [118]:
print(arr)
print(arr.ndim, arr.shape)

[[[5 2 8]
  [1 6 7]]

 [[4 9 3]
  [0 2 1]]]
3 (2, 2, 3)


In [119]:
# axis=-1 배열의 가장 안쪽 1차원 배열을 오름차순 정렬
# np.sort()힘수의 axis 기본값은 -1
np.sort(arr)

array([[[2, 5, 8],
        [1, 6, 7]],

       [[3, 4, 9],
        [0, 1, 2]]])

In [121]:
arr

array([[[5, 2, 8],
        [1, 6, 7]],

       [[4, 9, 3],
        [0, 2, 1]]])

In [120]:
np.sort(arr, axis=0) #가로

array([[[4, 2, 3],
        [0, 2, 1]],

       [[5, 9, 8],
        [1, 6, 7]]])

In [123]:
arr

array([[[5, 2, 8],
        [1, 6, 7]],

       [[4, 9, 3],
        [0, 2, 1]]])

In [122]:
np.sort(arr, axis=1) #세로

array([[[1, 2, 7],
        [5, 6, 8]],

       [[0, 2, 1],
        [4, 9, 3]]])

# argsort()
* 자료 중 값이 작은 것에서 큰 순으로 원래 자리의 인덱스 출력

In [124]:
g = np.array([5, 0.5, -7, 42, 10, 0])
g

array([ 5. ,  0.5, -7. , 42. , 10. ,  0. ])

In [126]:
s = g.argsort()
s

array([2, 5, 1, 0, 4, 3])

In [128]:
g[s][::-1]

array([42. , 10. ,  5. ,  0.5,  0. , -7. ])

In [134]:
g

array([ 5. ,  0.5, -7. , 42. , 10. ,  0. ])

# 최대값/최소값 위치 출력(argmax/argmin)
* 인덱스만 출력

In [135]:
# g[3]
g[np.argmax(g)]

np.float64(42.0)

In [136]:
g[np.argmin(g)]

np.float64(-7.0)

# np.where(조건, 참 거짓) 3항 연산

In [137]:
num = np.arange(1, 11)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [142]:
result = []
for i in num:
    if i % 2 == 0:
        result.append("짝수")
    else:
        result.append("홀수")
print(type(result))
result = np.array(result)
result

<class 'list'>


array(['홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수'],
      dtype='<U2')

In [144]:
num % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [143]:
np.where(num % 2 == 0, "짝수", "홀수")

array(['홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수'],
      dtype='<U2')

# 배열 합치기 np.concatenate() pd.concat()

In [148]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)
print(a, a.shape, a.ndim)
print(b, b.shape, b.ndim)

[[1 2]
 [3 4]] (2, 2) 2
[[5 6]
 [7 8]] (2, 2) 2


* np.concatenate((a,b))
* 합치는 기본 방향은 axis=0 행이 늘어남, 아래로 붙음
* axis = 1 열이 늘어남, 옆으로 붙음

In [150]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [151]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# 합치는 방향의 모양이 일치하지 않으면 합치기 X

In [152]:
c = np.array([5,6])
c

array([5, 6])

In [155]:
print(a.ndim) #2차원
a 

2


array([[1, 2],
       [3, 4]])

In [156]:
print(c.ndim) #1차원

1


In [154]:
np.concatenate((a,c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [157]:
c1 = np.array([[5,6]])
print(c1.ndim)
c1

2


array([[5, 6]])

In [158]:
np.concatenate((a,c1))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [159]:
a

array([[1, 2],
       [3, 4]])

In [160]:
c1

array([[5, 6]])

In [161]:
np.concatenate((a,c1), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [165]:
d = np.array([[1,2,3]])
print(d.ndim, d.shape)
d

2 (1, 3)


array([[1, 2, 3]])

In [166]:
np.concatenate((a,d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

* 행방향 axis=0 으로 합칠 때는 차원과 열의 개수가 같아야만 합쳐짐
* 열방향 axis=1로 합칠 때는 차원과 행의 개수가 같아야만 합쳐짐

# 전치 행렬 만들기
* .transpose(), .T
* 행과 열을 바꿔줌 

In [180]:
h2 = np.arange(1,7).reshape(2,3)
h2

array([[1, 2, 3],
       [4, 5, 6]])

In [171]:
a

array([[1, 2],
       [3, 4]])

In [172]:
np.concatenate((a,h))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [174]:
h.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [178]:
a.shape

(2, 2)

In [181]:
h2.shape

(2, 3)

In [183]:
np.concatenate((a, h2),axis=1)

array([[1, 2, 1, 2, 3],
       [3, 4, 4, 5, 6]])

# 브로드 캐스팅
* 벡터와 스칼라, 혹은 매트릭스와 벡터를 연산할 떄 자동으로 행렬 크기를 맞춰주는 것

In [184]:
a = np.arange(1, 16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [185]:
a + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [186]:
b = np.array([10, 20, 30, 40, 50])
print(b, b.ndim, b.shape)

[10 20 30 40 50] 1 (5,)


In [187]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [188]:
a + b

array([[11, 22, 33, 44, 55],
       [16, 27, 38, 49, 60],
       [21, 32, 43, 54, 65]])

In [189]:
c = np.array([[10, 20, 30, 40, 50]])
print(c, c.ndim, c.shape)

[[10 20 30 40 50]] 2 (1, 5)


In [191]:
print(c.T.shape)
c.T

(5, 1)


array([[10],
       [20],
       [30],
       [40],
       [50]])

In [192]:
print(a.shape)
a

(3, 5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

# 축(axis)기반 집계 연산

In [194]:
mat = np.array([[1,2,3], [4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [195]:
# 전체 요소 합
np.sum(mat)

np.int64(21)

In [196]:
# 열별 합 
np.sum(mat, axis=0)

array([5, 7, 9])

In [197]:
# 행별 합
np.sum(mat, axis=1)

array([ 6, 15])

# 배열 초기화 함수(zeros, ones, full, zeros_like)

In [198]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [199]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [200]:
np.full((2,3,4,5), 7)

array([[[[7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7]],

        [[7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7]],

        [[7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7]]],


       [[[7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7]],

        [[7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7]],

        [[7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7]]]])

In [201]:
base = np.arange(6).reshape(2,3)
base

array([[0, 1, 2],
       [3, 4, 5]])

In [202]:
np.zeros_like(base)

array([[0, 0, 0],
       [0, 0, 0]])

# 계산하기

In [203]:
# 행은 날짜, 열 지점별 수입
sales = np.array([
    [100, 120, 130],
    [90, 160, 110],
    [200, 180, 150] 
])
sales

array([[100, 120, 130],
       [ 90, 160, 110],
       [200, 180, 150]])

In [206]:
print("총 매출 합계:", np.sum(sales))

총 매출 합계: 1240


In [207]:
# 지점별 합계 
print("지점별(열) 합계:",np.sum(sales, axis=0))

일자별(열) 합계: [390 460 390]


In [208]:
# 일자별(행)
print("일자별(행) 합계:",np.sum(sales, axis=1))

일자별(행) 합계: [350 360 530]


In [209]:
# 전체평균
np.mean(sales)

np.float64(137.77777777777777)

In [210]:
# 지점별 평균
np.mean(sales, axis=0)

array([130.        , 153.33333333, 130.        ])

In [211]:
# 일자별 평균
np.mean(sales, axis=1)

array([116.66666667, 120.        , 176.66666667])

In [213]:
# 누적합 cumsum
cashflow = np.array([[100, -20, 50, -10]])
print("누적잔고:", np.cumsum(cashflow))

누적잔고: [100  80 130 120]


In [214]:
# 누적 비율 계산
rates = np.array([1.01, 1.03, 0.99, 1.05])
rates

array([1.01, 1.03, 0.99, 1.05])

In [215]:
# 경제성장률이 2019 3%, 2020 5%, 2021 4%, 2022 -5%
print("누적 성장률:", np.cumprod(rates))
#cumpord : 곱셈

누적 성장률: [1.01       1.0403     1.029897   1.08139185]


### 분산, 표준편차

In [217]:
classA = np.array([70, 72, 68, 69, 71])
classB = np.array([50, 90, 30, 100, 10])

In [222]:
# 평균
print("A반의 평균:",np.mean(classA))
print("B반의 평균:",np.mean(classB))

A반의 평균: 70.0
B반의 평균: 56.0


In [221]:
print("B반의 평균:",np.mean(classB))

B반의 평균: 56.0


In [223]:
# 분산
print("A반의 분산:",np.var(classA))
print("B반의 분산:",np.var(classB))

A반의 평균: 2.0
B반의 평균: 1184.0


In [224]:
# 표준편차
print("A반의 표준편차:",np.std(classA))
print("B반의 표준편차:",np.std(classB))

A반의 표준편차: 1.4142135623730951
B반의 표준편차: 34.40930106817051


# 고유값과 빈도 구하기 unique

In [225]:
brands = np.array(["AAPL","TSLA","AAPL","NVDA","TSLA","GOOGL",
                  "AAPL","TSLA","AAPL","NVDA","TSLA","GOOGL",
                  "AAPL","TSLA","AAPL","NVDA","TSLA","GOOGL",
                  "AAPL","TSLA","AAPL","NVDA","TSLA","GOOGL",
                  "AAPL","TSLA","AAPL","NVDA","TSLA","GOOGL"])

In [226]:
np.unique(brands)

array(['AAPL', 'GOOGL', 'NVDA', 'TSLA'], dtype='<U5')

In [227]:
np.unique(brands,return_counts=True)

(array(['AAPL', 'GOOGL', 'NVDA', 'TSLA'], dtype='<U5'),
 array([10,  5,  5, 10]))

# 삼각행렬 인덱스(triu_indixes / tril_indices)
* 상관계수 행렬, 공분산 행렬, 코사인 유사도 행렬들은 행과 열이 대칭인 대칭행렬
* 중복을 줄이기 위해서 위쪽 삼각형 또는 아래쪽 삼각형만 다룰 때 사용
* np.triu_indices(n): n x n 행렬에서 위 삼각형의 위치 좌표를 출력
* np.triu_indices(n): n x n 행렬에서 아래 삼각형의 위치 좌표를 출력

### mask
* 배열 안의 각 요소가 조건을 만족하면 True, 만족하지 않으면 False 를 갖도록 함

In [229]:
# 출력은 행, 열 순으로 나옴 
mask_up = np.zeros((3,3))
mask_up

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [231]:
row_up, col_up = np.triu_indices(3)
print(row_up)
print(col_up)

[0 0 0 1 1 2]
[0 1 2 1 2 2]


In [234]:
mask_up[row_up, col_up]=1

In [235]:
mask_up

array([[1., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.]])

In [244]:
row_bottom, col_bottom = np.tril_indices(3)

In [245]:
mask_up[row_bottom, col_bottom] = 3
mask_up

array([[3., 1., 1.],
       [3., 3., 1.],
       [3., 3., 3.]])

# 인덱싱,  슬라이싱

In [237]:
z = np.arange(1,31).reshape(5, -1)
z

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [238]:
z[2, 2]

np.int64(15)

In [239]:
z[:3,:3]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]])

In [240]:
z[2:4, 2:4]

array([[15, 16],
       [21, 22]])

In [241]:
z[2:6,2:7:2]

array([[15, 17],
       [21, 23],
       [27, 29]])

In [242]:
z[[0, 0, 0, 1, 1, 2], [0, 1, 2, 1, 2, 2]] = 0

In [243]:
z

array([[ 0,  0,  0,  4,  5,  6],
       [ 7,  0,  0, 10, 11, 12],
       [13, 14,  0, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])