# numpy
* Nemerical Python 과학적, 산업적 연산을 위한 패키지
* 다차원 배열, 행렬 연산에 주로 사용
* numpy는 python의 list와 비슷한 자료형
* 순서가 있는 자료형
* 인덱싱, 슬라이싱 가능
* 반복문에 넣어서 한개씩 꺼내는 것도 가능 
* 파이썬 list와의 차이점은 자료형이 1개만 들어간다는 점이 다르다. 

# 차원
* 0차원 = 점 . 스칼라 a = 10
* 1차원 = 선 ------- 벡터, 배열, list, tuple
  * 벡터(vector): 방향을 가진 데이터 
  * 행벡터: 행이 1개인 벡터 [1,2,3,4]
  * 열벡터: 열이 1개인 벡터<br> 
            [[1],<br>
             [2],<br>
             [3],<br>
             [4]]
* 2차원 = 면, 가로, 세로, DB테이블, excel의 sheet, 행렬, DataFrame, matrix
* 3차원 = 입체, 가로, 세로, 깊이, 정육면체, 주사위
* 4차원 = 3차원 요소가 2개 이상 묶여 있는 상태
* 5차원 = 4차원 요소가 2개 이상 묶여 있는 상태 

* 2차원 데이터가 여러개 묶여있는 게 3차원 
* 3차원 // 4차원 

In [1]:
import pandas as pd
import numpy as np

In [2]:
#numpy의 기본 자료형 nd.array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
a[0]

np.int64(1)

In [5]:
print(a[-1])

5


In [6]:
print(a[:3])

[1 2 3]


* 차원을 출력하는 메서드 .ndim
* 차원의 형태를 출력하는 메서드 .shape

In [7]:
# 스칼라, 0차원,
s = 10

In [8]:
s.ndim

AttributeError: 'int' object has no attribute 'ndim'

In [10]:
# a는 방향이 없는 벡터이므로 1차원
a.ndim

1

In [12]:
# 데이터가 5개 있는 방향 없는 벡터
a.shape

(5,)

In [13]:
# 세로로 방향을 가진 열벡터
a2 = np.array([[1],[2],[3],[4],[5]])
a2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [14]:
print(a2.ndim)
print(a2.shape)

2
(5, 1)


In [16]:
# 행벡터 2차원 행이 1개인 벡터 
a3 = np.array([[1,2,3,4,5]])
print(a3.ndim)
print(a3.shape)

2
(1, 5)


In [18]:
# 2차원 데이터 matrix, dataframe
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
print(c.ndim)
print(c.shape)

2
(2, 5)


In [22]:
# 3차원 데이터
d = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])
d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [21]:
print(d.ndim)
print(d.shape)
# 뒤에 있는 게 무조건 행과 열! (2행 5열짜리 2개 있다는 의미)

3
(2, 2, 5)


In [23]:
# 4차원 데이터
e = np.array([[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]],[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]]])
e

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]],


       [[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]])

In [24]:
print(e.ndim)
print(e.shape)

4
(2, 3, 2, 5)


In [25]:
# 5차원 데이터
f = np.array([[[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]],[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]]],[[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]],[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]]]])
f

array([[[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]],



       [[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]]])

In [26]:
print(f.ndim)
print(f.shape)

5
(2, 2, 3, 2, 5)


# numpy를 사용하는 이유
* 행렬 연산이 쉽고 빠르기 때문

In [27]:
# 스칼라 연산
a = 10
b = 5
scalar = a + b
print(scalar)

15


In [28]:
# 1차원 벡터 데이터의 연산 
b1 = [1,2,3,4,5]

In [29]:
# b1의 모든 요소에 10을 곱한 후 다시 리스트로 만드세요
result = []
for num in b1:
    result.append(num*10)
result

[10, 20, 30, 40, 50]

In [30]:
result2 = [num*10 for num in b1]
result2

[10, 20, 30, 40, 50]

In [33]:
a2 * 10

array([[10],
       [20],
       [30],
       [40],
       [50]])

In [35]:
a3 * 10

array([[10, 20, 30, 40, 50]])

In [42]:
c.shape

(2, 5)

In [50]:
result = []
for num1 in c:
    temp = []
    for num2 in num1:
        temp.append(num2*10)
    result.append(temp)
result

[[np.int64(10), np.int64(20), np.int64(30), np.int64(40), np.int64(50)],
 [np.int64(60), np.int64(70), np.int64(80), np.int64(90), np.int64(100)]]

In [48]:
np.array(result).shape

(5,)

In [46]:
c * 10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [47]:
d * 10

array([[[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100]],

       [[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100]]])

In [51]:
d.shape

(2, 2, 5)